export const validationMessage = (label?: string) => ({
  200: () => 'Successfully retrieved data',
  201: () => `${label || 'Data'} created successfully`,
  402: () => 'Invalid field',
  400: () => 'Please check your submitted data',
  401: () => 'Sorry, you do not have access',
  404: () => `${label || 'Data'} not found`,
  408: () => 'Please check your internet connection!',
  500: () => 'Server error occurred. Please try again later',
  failedCreate: `Failed to create ${label || 'form'}. Please check your form.`,
  failedLogin: (method: 'Email' | 'Phone number') => `Invalid ${method} or password`,
  failedUpdate: `Failed to update ${label || 'form'}. Please check your form.`,
  unstableNetwork: `Unstable internet connection`,
  noNetwork: `No internet connection`,
  unstableNetworkDesc: `There was an error with your internet connection. Please make sure you are connected to the internet and reload your browser`,
  required: () => `${label} is required`,
  invalidField: () => `${label} is invalid`,
  minChar: (length: number) => `${label} must be at least ${length} characters`,
  duplicateValue: `${label || 'This value'} is already in use`,
  updated: `${label || 'Data'} updated successfully`,
  deleted: `${label || 'Data'} deleted successfully`,
  min: (min: number) => `Minimum ${label} is ${min}`,
  max: (max: number) => `Maximum ${label} is ${max}`,
  saved: `${label || 'Data'} saved successfully`,
});
